export * from './ClientCreateDTO'
export * from './ClientUpdateDTO'
export * from './DocumentCreateDTO'
export * from './DepositUpdateDTO'
export * from './PaymentMonthlyUpdateDTO'
export * from './PaymentUpdateDTO'
